# Generated by Django 4.1.5 on 2023-01-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypesAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип объявления')),
            ],
            options={
                'verbose_name': 'Тип объявления',
                'verbose_name_plural': 'Типы объявления',
            },
        ),
    ]
