# Generated by Django 4.1.5 on 2023-01-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('types_ads', '0001_initial'),
        ('cities', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type_ads', models.CharField(max_length=255, verbose_name='Тип объявления')),
                ('adress', models.TextField(verbose_name='Адрес')),
                ('photo', models.ImageField(upload_to='ads/photos', verbose_name='Фото')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='author.author', verbose_name='Автор')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='cities.cities', verbose_name='Город')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='types_ads.typesads', verbose_name='Тип объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
