# Generated by Django 4.1.5 on 2023-01-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_favouriteadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='type_ads',
        ),
    ]
